[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = ["python -m virtualenv .venv", ".venv/bin/pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = ".venv/bin/python dudas_jump_monitor.py"
